// flow-typed signature: 6d7936ab664000446b63e2b0bf8c872b
// flow-typed version: <<STUB>>/agentkeepalive_v^4.0.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'agentkeepalive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'agentkeepalive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'agentkeepalive/browser' {
  declare module.exports: any;
}

declare module 'agentkeepalive/lib/agent' {
  declare module.exports: any;
}

declare module 'agentkeepalive/lib/constants' {
  declare module.exports: any;
}

declare module 'agentkeepalive/lib/https_agent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'agentkeepalive/browser.js' {
  declare module.exports: $Exports<'agentkeepalive/browser'>;
}
declare module 'agentkeepalive/index' {
  declare module.exports: $Exports<'agentkeepalive'>;
}
declare module 'agentkeepalive/index.js' {
  declare module.exports: $Exports<'agentkeepalive'>;
}
declare module 'agentkeepalive/lib/agent.js' {
  declare module.exports: $Exports<'agentkeepalive/lib/agent'>;
}
declare module 'agentkeepalive/lib/constants.js' {
  declare module.exports: $Exports<'agentkeepalive/lib/constants'>;
}
declare module 'agentkeepalive/lib/https_agent.js' {
  declare module.exports: $Exports<'agentkeepalive/lib/https_agent'>;
}
