// flow-typed signature: 2e0751497d9f6b0c27717fd2832372b6
// flow-typed version: <<STUB>>/auto-changelog_v^1.8.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auto-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auto-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auto-changelog/lib/commits' {
  declare module.exports: any;
}

declare module 'auto-changelog/lib/index' {
  declare module.exports: any;
}

declare module 'auto-changelog/lib/releases' {
  declare module.exports: any;
}

declare module 'auto-changelog/lib/remote' {
  declare module.exports: any;
}

declare module 'auto-changelog/lib/run' {
  declare module.exports: any;
}

declare module 'auto-changelog/lib/template' {
  declare module.exports: any;
}

declare module 'auto-changelog/lib/utils' {
  declare module.exports: any;
}

declare module 'auto-changelog/scripts/generate-test-data' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auto-changelog/lib/commits.js' {
  declare module.exports: $Exports<'auto-changelog/lib/commits'>;
}
declare module 'auto-changelog/lib/index.js' {
  declare module.exports: $Exports<'auto-changelog/lib/index'>;
}
declare module 'auto-changelog/lib/releases.js' {
  declare module.exports: $Exports<'auto-changelog/lib/releases'>;
}
declare module 'auto-changelog/lib/remote.js' {
  declare module.exports: $Exports<'auto-changelog/lib/remote'>;
}
declare module 'auto-changelog/lib/run.js' {
  declare module.exports: $Exports<'auto-changelog/lib/run'>;
}
declare module 'auto-changelog/lib/template.js' {
  declare module.exports: $Exports<'auto-changelog/lib/template'>;
}
declare module 'auto-changelog/lib/utils.js' {
  declare module.exports: $Exports<'auto-changelog/lib/utils'>;
}
declare module 'auto-changelog/scripts/generate-test-data.js' {
  declare module.exports: $Exports<'auto-changelog/scripts/generate-test-data'>;
}
