// flow-typed signature: b0e2533ec934dd7b6c93670db9f06b86
// flow-typed version: <<STUB>>/babel-preset-next_v^1.2.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'babel-preset-next/index' {
  declare module.exports: $Exports<'babel-preset-next'>;
}
declare module 'babel-preset-next/index.js' {
  declare module.exports: $Exports<'babel-preset-next'>;
}
