// flow-typed signature: bb229cebc81e08ab1a7906fd01d6f597
// flow-typed version: <<STUB>>/buildify_v^0.4.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buildify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buildify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'buildify/bin/cli' {
  declare module.exports: any;
}

declare module 'buildify/tasks' {
  declare module.exports: any;
}

declare module 'buildify/test/index.test' {
  declare module.exports: any;
}

declare module 'buildify/test/tasks/tasks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'buildify/bin/cli.js' {
  declare module.exports: $Exports<'buildify/bin/cli'>;
}
declare module 'buildify/index' {
  declare module.exports: $Exports<'buildify'>;
}
declare module 'buildify/index.js' {
  declare module.exports: $Exports<'buildify'>;
}
declare module 'buildify/tasks.js' {
  declare module.exports: $Exports<'buildify/tasks'>;
}
declare module 'buildify/test/index.test.js' {
  declare module.exports: $Exports<'buildify/test/index.test'>;
}
declare module 'buildify/test/tasks/tasks.js' {
  declare module.exports: $Exports<'buildify/test/tasks/tasks'>;
}
