// flow-typed signature: 50c5a5706448d85e85f3df82d7295e5a
// flow-typed version: <<STUB>>/canned_v^0.3.12/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'canned'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'canned' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'canned/lib/canned' {
  declare module.exports: any;
}

declare module 'canned/lib/lookup' {
  declare module.exports: any;
}

declare module 'canned/lib/response' {
  declare module.exports: any;
}

declare module 'canned/lib/utils' {
  declare module.exports: any;
}

declare module 'canned/spec/canned.spec' {
  declare module.exports: any;
}

declare module 'canned/spec/lookup.spec' {
  declare module.exports: any;
}

declare module 'canned/spec/test_responses/_multiple_type.get' {
  declare module.exports: any;
}

// Filename aliases
declare module 'canned/index' {
  declare module.exports: $Exports<'canned'>;
}
declare module 'canned/index.js' {
  declare module.exports: $Exports<'canned'>;
}
declare module 'canned/lib/canned.js' {
  declare module.exports: $Exports<'canned/lib/canned'>;
}
declare module 'canned/lib/lookup.js' {
  declare module.exports: $Exports<'canned/lib/lookup'>;
}
declare module 'canned/lib/response.js' {
  declare module.exports: $Exports<'canned/lib/response'>;
}
declare module 'canned/lib/utils.js' {
  declare module.exports: $Exports<'canned/lib/utils'>;
}
declare module 'canned/spec/canned.spec.js' {
  declare module.exports: $Exports<'canned/spec/canned.spec'>;
}
declare module 'canned/spec/lookup.spec.js' {
  declare module.exports: $Exports<'canned/spec/lookup.spec'>;
}
declare module 'canned/spec/test_responses/_multiple_type.get.js' {
  declare module.exports: $Exports<'canned/spec/test_responses/_multiple_type.get'>;
}
