// flow-typed signature: 5ceb7f51aedb6c0eb8d650d4281e45f9
// flow-typed version: <<STUB>>/datatables.net_v^1.10.15/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'datatables.net'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'datatables.net' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'datatables.net/js/jquery.dataTables' {
  declare module.exports: any;
}

declare module 'datatables.net/js/jquery.dataTables.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'datatables.net/js/jquery.dataTables.js' {
  declare module.exports: $Exports<'datatables.net/js/jquery.dataTables'>;
}
declare module 'datatables.net/js/jquery.dataTables.min.js' {
  declare module.exports: $Exports<'datatables.net/js/jquery.dataTables.min'>;
}
