// flow-typed signature: 302e4feffb8a81d7eb7d7fa552c2346d
// flow-typed version: <<STUB>>/eslint-plugin-extra-rules_v0.0.0-development/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-extra-rules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-extra-rules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-extra-rules/camel_case' {
  declare module.exports: any;
}

declare module 'eslint-plugin-extra-rules/no-commented-out-code' {
  declare module.exports: any;
}

declare module 'eslint-plugin-extra-rules/no-for-loops' {
  declare module.exports: any;
}

declare module 'eslint-plugin-extra-rules/no-long-files' {
  declare module.exports: any;
}

declare module 'eslint-plugin-extra-rules/no-single-line-objects' {
  declare module.exports: any;
}

declare module 'eslint-plugin-extra-rules/potential-point-free' {
  declare module.exports: any;
}

declare module 'eslint-plugin-extra-rules/src/is-constant' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-extra-rules/camel_case.js' {
  declare module.exports: $Exports<'eslint-plugin-extra-rules/camel_case'>;
}
declare module 'eslint-plugin-extra-rules/index' {
  declare module.exports: $Exports<'eslint-plugin-extra-rules'>;
}
declare module 'eslint-plugin-extra-rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-extra-rules'>;
}
declare module 'eslint-plugin-extra-rules/no-commented-out-code.js' {
  declare module.exports: $Exports<'eslint-plugin-extra-rules/no-commented-out-code'>;
}
declare module 'eslint-plugin-extra-rules/no-for-loops.js' {
  declare module.exports: $Exports<'eslint-plugin-extra-rules/no-for-loops'>;
}
declare module 'eslint-plugin-extra-rules/no-long-files.js' {
  declare module.exports: $Exports<'eslint-plugin-extra-rules/no-long-files'>;
}
declare module 'eslint-plugin-extra-rules/no-single-line-objects.js' {
  declare module.exports: $Exports<'eslint-plugin-extra-rules/no-single-line-objects'>;
}
declare module 'eslint-plugin-extra-rules/potential-point-free.js' {
  declare module.exports: $Exports<'eslint-plugin-extra-rules/potential-point-free'>;
}
declare module 'eslint-plugin-extra-rules/src/is-constant.js' {
  declare module.exports: $Exports<'eslint-plugin-extra-rules/src/is-constant'>;
}
