// flow-typed signature: 73b57899dc76341f8ba39813a11fafcf
// flow-typed version: <<STUB>>/harp-minify_v^0.4.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'harp-minify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'harp-minify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'harp-minify/lib/index' {
  declare module.exports: any;
}

declare module 'harp-minify/test/fixtures/max' {
  declare module.exports: any;
}

declare module 'harp-minify/test/fixtures/min' {
  declare module.exports: any;
}

declare module 'harp-minify/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'harp-minify/lib/index.js' {
  declare module.exports: $Exports<'harp-minify/lib/index'>;
}
declare module 'harp-minify/test/fixtures/max.js' {
  declare module.exports: $Exports<'harp-minify/test/fixtures/max'>;
}
declare module 'harp-minify/test/fixtures/min.js' {
  declare module.exports: $Exports<'harp-minify/test/fixtures/min'>;
}
declare module 'harp-minify/test/index.js' {
  declare module.exports: $Exports<'harp-minify/test/index'>;
}
