// flow-typed signature: cdd0c3f25ae65d306f52abdefc1a85c2
// flow-typed version: <<STUB>>/lighthouse_v^3.2.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lighthouse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lighthouse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lighthouse/commitlint.config' {
  declare module.exports: any;
}

declare module 'lighthouse/docs/recipes/custom-audit/custom-config' {
  declare module.exports: any;
}

declare module 'lighthouse/docs/recipes/custom-audit/searchable-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/docs/recipes/custom-audit/searchable-gatherer' {
  declare module.exports: any;
}

declare module 'lighthouse/docs/recipes/gulp/gulpfile' {
  declare module.exports: any;
}

declare module 'lighthouse/jest.config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/bin' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/cli-flags' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/commands/commands' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/commands/list-audits' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/commands/list-trace-categories' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/index' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/printer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/run' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/sentry-prompt' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/cli/cli-flags-test' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/cli/index-test' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/cli/printer-test' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/cli/run-test' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/byte-efficiency/script' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/dobetterweb/dbw_tester' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/dobetterweb/empty_module' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/offline-ready-sw' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/perf/level-2' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/perf/level-3' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/perf/preload_tester' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/fixtures/static-server' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/global-mocha-hooks' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/a11y/a11y-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/a11y/expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/byte-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/byte-efficiency/expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/dbw-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/offline-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/offline-local/offline-expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/perf/expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa-expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa2-expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa3-expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/redirects-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/redirects/expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/run-smoke' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/seo-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/seo/expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/smokehouse' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-cli/test/smokehouse/tricky-tti/expectations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/accesskeys' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-allowed-attr' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-attr' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-children' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-parent' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-roles' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr-value' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/audio-caption' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/axe-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/button-name' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/bypass' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/color-contrast' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/definition-list' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/dlitem' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/document-title' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/duplicate-id' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/frame-title' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/html-has-lang' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/html-lang-valid' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/image-alt' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/input-image-alt' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/label' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/layout-table' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/link-name' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/list' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/listitem' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/custom-controls-labels' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/custom-controls-roles' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/focus-traps' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/focusable-controls' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/heading-levels' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/interactive-element-affordance' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/logical-tab-order' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/managed-focus' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/offscreen-content-hidden' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/use-landmarks' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/visual-order-follows-dom' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/meta-refresh' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/meta-viewport' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/object-alt' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/tabindex' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/td-headers-attr' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/th-has-data-cells' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/valid-lang' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/video-caption' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/accessibility/video-description' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/bootup-time' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/byte-efficiency-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/efficient-animated-content' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/offscreen-images' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/render-blocking-resources' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/total-byte-weight' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/unminified-css' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/unminified-javascript' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/unused-css-rules' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/unused-javascript' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-optimized-images' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-responsive-images' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-text-compression' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-webp-images' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/content-width' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/critical-request-chains' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/deprecations' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/appcache-manifest' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/doctype' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/dom-size' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/geolocation-on-start' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/js-libraries' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-document-write' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-vulnerable-libraries' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-websql' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/notification-on-start' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/uses-http2' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/dobetterweb/uses-passive-event-listeners' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/errors-in-console' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/final-screenshot' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/font-display' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/image-aspect-ratio' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/is-on-https' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/load-fast-enough-for-pwa' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/mainthread-work-breakdown' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/manifest-short-name-length' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/manual/manual-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/manual/pwa-cross-browser' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/manual/pwa-each-page-has-url' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/manual/pwa-page-transitions' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/metrics' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/metrics/estimated-input-latency' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/metrics/first-contentful-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/metrics/first-cpu-idle' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/metrics/first-meaningful-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/metrics/interactive' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/metrics/speed-index' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/mixed-content' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/multi-check-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/network-requests' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/predictive-perf' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/redirects-http' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/redirects' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/screenshot-thumbnails' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/canonical' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/font-size' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/hreflang' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/http-status-code' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/is-crawlable' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/link-text' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/manual/mobile-friendly' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/manual/structured-data' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/meta-description' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/plugins' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/seo/robots-txt' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/service-worker' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/splash-screen' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/themed-omnibox' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/time-to-first-byte' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/user-timings' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/uses-rel-preconnect' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/uses-rel-preload' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/viewport' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/violation-audit' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/webapp-install-banner' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/without-javascript' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/audits/works-offline' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/constants' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/default-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/full-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/lr-desktop-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/lr-mobile-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/mixed-content-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/perf-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/config/plots-config' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/computed-artifact' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/critical-request-chains' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/load-simulator' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/main-resource' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/main-thread-tasks' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/manifest-values' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/estimated-input-latency' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/first-contentful-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/first-cpu-idle' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/first-meaningful-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/interactive' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-estimated-input-latency' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-first-contentful-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-first-cpu-idle' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-interactive' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-metric' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-speed-index' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/metric' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/metrics/speed-index' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/network-analysis' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/network-records' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/network-throughput' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/new-computed-artifact' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/page-dependency-graph' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/pushed-requests' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/screenshots' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/speedline' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/computed/trace-of-tab' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/connections/connection' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/connections/cri' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/connections/extension' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/connections/raw' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/devtools-log' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/driver' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gather-runner' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/accessibility' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/cache-contents' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/chrome-console-messages' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/css-usage' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/appcache' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/doctype' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/domstats' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/js-libraries' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/optimized-images' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/response-compression' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/websql' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/fonts' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/gatherer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/html-without-javascript' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/http-redirect' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/image-usage' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/js-usage' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/manifest' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/mixed-content' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/offline' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/runtime-exceptions' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/scripts' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/canonical' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/crawlable-links' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/embedded-content' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/font-size' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/hreflang' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/meta-description' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/meta-robots' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/robots-txt' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/service-worker' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/start-url' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/theme-color' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/viewport-dimensions' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/gather/gatherers/viewport' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/index' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/arbitrary-equality-map' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/asset-saver' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/console-quieter' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/dependency-graph/base-node' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/dependency-graph/cpu-node' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/dependency-graph/network-node' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/dependency-graph/simulator/connection-pool' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/dependency-graph/simulator/dns-cache' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/dependency-graph/simulator/network-analyzer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/dependency-graph/simulator/simulator' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/dependency-graph/simulator/tcp-connection' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/element' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/empty-stub' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/emulation' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/file-namer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/i18n/i18n' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/i18n/locales' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/icons' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/lantern-trace-saver' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/lh-error' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/manifest-parser' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/network-recorder' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/network-request' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/page-functions' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/sentry' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/statistics' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/strings' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/task-groups' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/traces/pwmetrics-events' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/traces/tracing-processor' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/url-shim' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/lib/web-inspector' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/html-report-assets' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/renderer/category-renderer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/renderer/crc-details-renderer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/renderer/details-renderer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/renderer/dom' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/renderer/logger' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/renderer/performance-category-renderer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/renderer/psi' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/renderer/report-renderer' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/renderer/report-ui-features' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/html/renderer/util' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/report/report-generator' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/runner' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/scoring' {
  declare module.exports: any;
}

declare module 'lighthouse/lighthouse-core/scripts/manual-chrome-launcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lighthouse/commitlint.config.js' {
  declare module.exports: $Exports<'lighthouse/commitlint.config'>;
}
declare module 'lighthouse/docs/recipes/custom-audit/custom-config.js' {
  declare module.exports: $Exports<'lighthouse/docs/recipes/custom-audit/custom-config'>;
}
declare module 'lighthouse/docs/recipes/custom-audit/searchable-audit.js' {
  declare module.exports: $Exports<'lighthouse/docs/recipes/custom-audit/searchable-audit'>;
}
declare module 'lighthouse/docs/recipes/custom-audit/searchable-gatherer.js' {
  declare module.exports: $Exports<'lighthouse/docs/recipes/custom-audit/searchable-gatherer'>;
}
declare module 'lighthouse/docs/recipes/gulp/gulpfile.js' {
  declare module.exports: $Exports<'lighthouse/docs/recipes/gulp/gulpfile'>;
}
declare module 'lighthouse/jest.config.js' {
  declare module.exports: $Exports<'lighthouse/jest.config'>;
}
declare module 'lighthouse/lighthouse-cli/bin.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/bin'>;
}
declare module 'lighthouse/lighthouse-cli/cli-flags.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/cli-flags'>;
}
declare module 'lighthouse/lighthouse-cli/commands/commands.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/commands/commands'>;
}
declare module 'lighthouse/lighthouse-cli/commands/list-audits.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/commands/list-audits'>;
}
declare module 'lighthouse/lighthouse-cli/commands/list-trace-categories.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/commands/list-trace-categories'>;
}
declare module 'lighthouse/lighthouse-cli/index.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/index'>;
}
declare module 'lighthouse/lighthouse-cli/printer.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/printer'>;
}
declare module 'lighthouse/lighthouse-cli/run.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/run'>;
}
declare module 'lighthouse/lighthouse-cli/sentry-prompt.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/sentry-prompt'>;
}
declare module 'lighthouse/lighthouse-cli/test/cli/cli-flags-test.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/cli/cli-flags-test'>;
}
declare module 'lighthouse/lighthouse-cli/test/cli/index-test.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/cli/index-test'>;
}
declare module 'lighthouse/lighthouse-cli/test/cli/printer-test.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/cli/printer-test'>;
}
declare module 'lighthouse/lighthouse-cli/test/cli/run-test.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/cli/run-test'>;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/byte-efficiency/script.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-cli/test/fixtures/byte-efficiency/script'
  >;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/dobetterweb/dbw_tester.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-cli/test/fixtures/dobetterweb/dbw_tester'
  >;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/dobetterweb/empty_module.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-cli/test/fixtures/dobetterweb/empty_module'
  >;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/offline-ready-sw.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/fixtures/offline-ready-sw'>;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/perf/level-2.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/fixtures/perf/level-2'>;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/perf/level-3.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/fixtures/perf/level-3'>;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/perf/preload_tester.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/fixtures/perf/preload_tester'>;
}
declare module 'lighthouse/lighthouse-cli/test/fixtures/static-server.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/fixtures/static-server'>;
}
declare module 'lighthouse/lighthouse-cli/test/global-mocha-hooks.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/global-mocha-hooks'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/a11y/a11y-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/a11y/a11y-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/a11y/expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/a11y/expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/byte-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/byte-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/byte-efficiency/expectations.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-cli/test/smokehouse/byte-efficiency/expectations'
  >;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/dbw-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/dbw-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-cli/test/smokehouse/dobetterweb/dbw-expectations'
  >;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/offline-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/offline-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/offline-local/offline-expectations.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-cli/test/smokehouse/offline-local/offline-expectations'
  >;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/perf/expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/perf/expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/pwa-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa-expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/pwa-expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa2-expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/pwa2-expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/pwa3-expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/pwa3-expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/redirects-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/redirects-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/redirects/expectations.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-cli/test/smokehouse/redirects/expectations'
  >;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/run-smoke.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/run-smoke'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/seo-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/seo-config'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/seo/expectations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/seo/expectations'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/smokehouse.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-cli/test/smokehouse/smokehouse'>;
}
declare module 'lighthouse/lighthouse-cli/test/smokehouse/tricky-tti/expectations.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-cli/test/smokehouse/tricky-tti/expectations'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/accesskeys.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/accesskeys'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-allowed-attr.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/aria-allowed-attr'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-attr.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/aria-required-attr'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-children.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/aria-required-children'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-required-parent.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/aria-required-parent'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-roles.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/aria-roles'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr-value.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr-value'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/aria-valid-attr'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/audio-caption.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/audio-caption'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/axe-audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/axe-audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/button-name.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/button-name'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/bypass.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/bypass'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/color-contrast.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/color-contrast'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/definition-list.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/definition-list'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/dlitem.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/dlitem'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/document-title.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/document-title'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/duplicate-id.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/duplicate-id'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/frame-title.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/frame-title'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/html-has-lang.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/html-has-lang'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/html-lang-valid.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/html-lang-valid'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/image-alt.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/image-alt'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/input-image-alt.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/input-image-alt'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/label.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/label'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/layout-table.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/layout-table'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/link-name.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/link-name'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/list.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/list'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/listitem.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/listitem'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/custom-controls-labels.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/custom-controls-labels'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/custom-controls-roles.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/custom-controls-roles'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/focus-traps.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/focus-traps'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/focusable-controls.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/focusable-controls'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/heading-levels.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/heading-levels'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/interactive-element-affordance.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/interactive-element-affordance'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/logical-tab-order.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/logical-tab-order'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/managed-focus.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/managed-focus'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/offscreen-content-hidden.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/offscreen-content-hidden'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/use-landmarks.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/use-landmarks'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/manual/visual-order-follows-dom.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/manual/visual-order-follows-dom'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/meta-refresh.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/meta-refresh'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/meta-viewport.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/meta-viewport'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/object-alt.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/object-alt'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/tabindex.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/tabindex'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/td-headers-attr.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/td-headers-attr'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/th-has-data-cells.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/th-has-data-cells'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/valid-lang.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/valid-lang'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/video-caption.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/accessibility/video-caption'>;
}
declare module 'lighthouse/lighthouse-core/audits/accessibility/video-description.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/accessibility/video-description'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/bootup-time.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/bootup-time'>;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/byte-efficiency-audit.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/byte-efficiency-audit'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/efficient-animated-content.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/efficient-animated-content'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/offscreen-images.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/offscreen-images'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/render-blocking-resources.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/render-blocking-resources'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/total-byte-weight.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/total-byte-weight'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/unminified-css.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/unminified-css'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/unminified-javascript.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/unminified-javascript'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/unused-css-rules.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/unused-css-rules'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/unused-javascript.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/unused-javascript'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/uses-long-cache-ttl'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-optimized-images.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/uses-optimized-images'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-responsive-images.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/uses-responsive-images'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-text-compression.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/uses-text-compression'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/byte-efficiency/uses-webp-images.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/byte-efficiency/uses-webp-images'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/content-width.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/content-width'>;
}
declare module 'lighthouse/lighthouse-core/audits/critical-request-chains.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/critical-request-chains'>;
}
declare module 'lighthouse/lighthouse-core/audits/deprecations.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/deprecations'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/appcache-manifest.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/dobetterweb/appcache-manifest'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/doctype.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/doctype'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/dom-size.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/dom-size'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/dobetterweb/external-anchors-use-rel-noopener'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/geolocation-on-start.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/dobetterweb/geolocation-on-start'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/js-libraries.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/js-libraries'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-document-write.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/dobetterweb/no-document-write'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-vulnerable-libraries.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/dobetterweb/no-vulnerable-libraries'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/no-websql.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/no-websql'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/notification-on-start.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/dobetterweb/notification-on-start'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/dobetterweb/password-inputs-can-be-pasted-into'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/uses-http2.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/dobetterweb/uses-http2'>;
}
declare module 'lighthouse/lighthouse-core/audits/dobetterweb/uses-passive-event-listeners.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/dobetterweb/uses-passive-event-listeners'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/errors-in-console.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/errors-in-console'>;
}
declare module 'lighthouse/lighthouse-core/audits/final-screenshot.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/final-screenshot'>;
}
declare module 'lighthouse/lighthouse-core/audits/font-display.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/font-display'>;
}
declare module 'lighthouse/lighthouse-core/audits/image-aspect-ratio.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/image-aspect-ratio'>;
}
declare module 'lighthouse/lighthouse-core/audits/is-on-https.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/is-on-https'>;
}
declare module 'lighthouse/lighthouse-core/audits/load-fast-enough-for-pwa.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/load-fast-enough-for-pwa'>;
}
declare module 'lighthouse/lighthouse-core/audits/mainthread-work-breakdown.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/mainthread-work-breakdown'>;
}
declare module 'lighthouse/lighthouse-core/audits/manifest-short-name-length.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/manifest-short-name-length'>;
}
declare module 'lighthouse/lighthouse-core/audits/manual/manual-audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/manual/manual-audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/manual/pwa-cross-browser.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/manual/pwa-cross-browser'>;
}
declare module 'lighthouse/lighthouse-core/audits/manual/pwa-each-page-has-url.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/manual/pwa-each-page-has-url'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/manual/pwa-page-transitions.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/manual/pwa-page-transitions'>;
}
declare module 'lighthouse/lighthouse-core/audits/metrics.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/metrics'>;
}
declare module 'lighthouse/lighthouse-core/audits/metrics/estimated-input-latency.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/metrics/estimated-input-latency'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/metrics/first-contentful-paint.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/metrics/first-contentful-paint'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/metrics/first-cpu-idle.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/metrics/first-cpu-idle'>;
}
declare module 'lighthouse/lighthouse-core/audits/metrics/first-meaningful-paint.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/audits/metrics/first-meaningful-paint'
  >;
}
declare module 'lighthouse/lighthouse-core/audits/metrics/interactive.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/metrics/interactive'>;
}
declare module 'lighthouse/lighthouse-core/audits/metrics/speed-index.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/metrics/speed-index'>;
}
declare module 'lighthouse/lighthouse-core/audits/mixed-content.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/mixed-content'>;
}
declare module 'lighthouse/lighthouse-core/audits/multi-check-audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/multi-check-audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/network-requests.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/network-requests'>;
}
declare module 'lighthouse/lighthouse-core/audits/predictive-perf.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/predictive-perf'>;
}
declare module 'lighthouse/lighthouse-core/audits/redirects-http.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/redirects-http'>;
}
declare module 'lighthouse/lighthouse-core/audits/redirects.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/redirects'>;
}
declare module 'lighthouse/lighthouse-core/audits/screenshot-thumbnails.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/screenshot-thumbnails'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/canonical.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/canonical'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/font-size.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/font-size'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/hreflang.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/hreflang'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/http-status-code.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/http-status-code'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/is-crawlable.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/is-crawlable'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/link-text.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/link-text'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/manual/mobile-friendly.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/manual/mobile-friendly'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/manual/structured-data.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/manual/structured-data'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/meta-description.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/meta-description'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/plugins.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/plugins'>;
}
declare module 'lighthouse/lighthouse-core/audits/seo/robots-txt.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/seo/robots-txt'>;
}
declare module 'lighthouse/lighthouse-core/audits/service-worker.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/service-worker'>;
}
declare module 'lighthouse/lighthouse-core/audits/splash-screen.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/splash-screen'>;
}
declare module 'lighthouse/lighthouse-core/audits/themed-omnibox.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/themed-omnibox'>;
}
declare module 'lighthouse/lighthouse-core/audits/time-to-first-byte.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/time-to-first-byte'>;
}
declare module 'lighthouse/lighthouse-core/audits/user-timings.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/user-timings'>;
}
declare module 'lighthouse/lighthouse-core/audits/uses-rel-preconnect.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/uses-rel-preconnect'>;
}
declare module 'lighthouse/lighthouse-core/audits/uses-rel-preload.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/uses-rel-preload'>;
}
declare module 'lighthouse/lighthouse-core/audits/viewport.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/viewport'>;
}
declare module 'lighthouse/lighthouse-core/audits/violation-audit.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/violation-audit'>;
}
declare module 'lighthouse/lighthouse-core/audits/webapp-install-banner.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/webapp-install-banner'>;
}
declare module 'lighthouse/lighthouse-core/audits/without-javascript.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/without-javascript'>;
}
declare module 'lighthouse/lighthouse-core/audits/works-offline.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/audits/works-offline'>;
}
declare module 'lighthouse/lighthouse-core/config/config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/config'>;
}
declare module 'lighthouse/lighthouse-core/config/constants.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/constants'>;
}
declare module 'lighthouse/lighthouse-core/config/default-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/default-config'>;
}
declare module 'lighthouse/lighthouse-core/config/full-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/full-config'>;
}
declare module 'lighthouse/lighthouse-core/config/lr-desktop-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/lr-desktop-config'>;
}
declare module 'lighthouse/lighthouse-core/config/lr-mobile-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/lr-mobile-config'>;
}
declare module 'lighthouse/lighthouse-core/config/mixed-content-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/mixed-content-config'>;
}
declare module 'lighthouse/lighthouse-core/config/perf-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/perf-config'>;
}
declare module 'lighthouse/lighthouse-core/config/plots-config.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/config/plots-config'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/computed-artifact.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/computed-artifact'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/critical-request-chains.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/critical-request-chains'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/load-simulator.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/load-simulator'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/main-resource.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/main-resource'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/main-thread-tasks.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/main-thread-tasks'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/manifest-values.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/manifest-values'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/estimated-input-latency.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/estimated-input-latency'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/first-contentful-paint.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/first-contentful-paint'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/first-cpu-idle.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/first-cpu-idle'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/first-meaningful-paint.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/first-meaningful-paint'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/interactive.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/interactive'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-estimated-input-latency.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/lantern-estimated-input-latency'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-first-contentful-paint.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/lantern-first-contentful-paint'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-first-cpu-idle.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/lantern-first-cpu-idle'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/lantern-first-meaningful-paint'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-interactive.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/lantern-interactive'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-metric.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/lantern-metric'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/lantern-speed-index.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/lantern-speed-index'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/metric.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/metrics/metric'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/metrics/speed-index.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/metrics/speed-index'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/network-analysis.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/network-analysis'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/network-records.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/network-records'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/network-throughput.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/network-throughput'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/new-computed-artifact.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/new-computed-artifact'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/page-dependency-graph.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/computed/page-dependency-graph'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/computed/pushed-requests.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/pushed-requests'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/screenshots.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/screenshots'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/speedline.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/speedline'>;
}
declare module 'lighthouse/lighthouse-core/gather/computed/trace-of-tab.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/computed/trace-of-tab'>;
}
declare module 'lighthouse/lighthouse-core/gather/connections/connection.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/connections/connection'>;
}
declare module 'lighthouse/lighthouse-core/gather/connections/cri.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/connections/cri'>;
}
declare module 'lighthouse/lighthouse-core/gather/connections/extension.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/connections/extension'>;
}
declare module 'lighthouse/lighthouse-core/gather/connections/raw.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/connections/raw'>;
}
declare module 'lighthouse/lighthouse-core/gather/devtools-log.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/devtools-log'>;
}
declare module 'lighthouse/lighthouse-core/gather/driver.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/driver'>;
}
declare module 'lighthouse/lighthouse-core/gather/gather-runner.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gather-runner'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/accessibility.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/accessibility'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/cache-contents.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/cache-contents'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/chrome-console-messages.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/chrome-console-messages'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/css-usage.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/css-usage'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/anchors-with-no-rel-noopener'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/appcache.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/appcache'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/doctype.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/doctype'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/domstats.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/domstats'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/js-libraries.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/js-libraries'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/optimized-images.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/optimized-images'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/password-inputs-with-prevented-paste'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/response-compression.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/response-compression'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/tags-blocking-first-paint'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/websql.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/dobetterweb/websql'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/fonts.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/fonts'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/gatherer.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/gatherer'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/html-without-javascript.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/html-without-javascript'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/http-redirect.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/http-redirect'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/image-usage.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/image-usage'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/js-usage.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/js-usage'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/manifest.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/manifest'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/mixed-content.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/mixed-content'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/offline.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/offline'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/runtime-exceptions.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/runtime-exceptions'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/scripts.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/scripts'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/canonical.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/seo/canonical'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/crawlable-links.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/seo/crawlable-links'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/embedded-content.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/seo/embedded-content'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/font-size.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/seo/font-size'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/hreflang.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/seo/hreflang'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/meta-description.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/seo/meta-description'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/meta-robots.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/seo/meta-robots'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/seo/robots-txt.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/seo/robots-txt'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/service-worker.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/service-worker'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/start-url.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/start-url'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/theme-color.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/theme-color'>;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/viewport-dimensions.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/gather/gatherers/viewport-dimensions'
  >;
}
declare module 'lighthouse/lighthouse-core/gather/gatherers/viewport.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/gather/gatherers/viewport'>;
}
declare module 'lighthouse/lighthouse-core/index.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/index'>;
}
declare module 'lighthouse/lighthouse-core/lib/arbitrary-equality-map.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/arbitrary-equality-map'>;
}
declare module 'lighthouse/lighthouse-core/lib/asset-saver.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/asset-saver'>;
}
declare module 'lighthouse/lighthouse-core/lib/console-quieter.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/console-quieter'>;
}
declare module 'lighthouse/lighthouse-core/lib/dependency-graph/base-node.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/dependency-graph/base-node'>;
}
declare module 'lighthouse/lighthouse-core/lib/dependency-graph/cpu-node.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/dependency-graph/cpu-node'>;
}
declare module 'lighthouse/lighthouse-core/lib/dependency-graph/network-node.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/dependency-graph/network-node'>;
}
declare module 'lighthouse/lighthouse-core/lib/dependency-graph/simulator/connection-pool.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/lib/dependency-graph/simulator/connection-pool'
  >;
}
declare module 'lighthouse/lighthouse-core/lib/dependency-graph/simulator/dns-cache.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/lib/dependency-graph/simulator/dns-cache'
  >;
}
declare module 'lighthouse/lighthouse-core/lib/dependency-graph/simulator/network-analyzer.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/lib/dependency-graph/simulator/network-analyzer'
  >;
}
declare module 'lighthouse/lighthouse-core/lib/dependency-graph/simulator/simulator.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/lib/dependency-graph/simulator/simulator'
  >;
}
declare module 'lighthouse/lighthouse-core/lib/dependency-graph/simulator/tcp-connection.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/lib/dependency-graph/simulator/tcp-connection'
  >;
}
declare module 'lighthouse/lighthouse-core/lib/element.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/element'>;
}
declare module 'lighthouse/lighthouse-core/lib/empty-stub.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/empty-stub'>;
}
declare module 'lighthouse/lighthouse-core/lib/emulation.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/emulation'>;
}
declare module 'lighthouse/lighthouse-core/lib/file-namer.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/file-namer'>;
}
declare module 'lighthouse/lighthouse-core/lib/i18n/i18n.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/i18n/i18n'>;
}
declare module 'lighthouse/lighthouse-core/lib/i18n/locales.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/i18n/locales'>;
}
declare module 'lighthouse/lighthouse-core/lib/icons.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/icons'>;
}
declare module 'lighthouse/lighthouse-core/lib/lantern-trace-saver.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/lantern-trace-saver'>;
}
declare module 'lighthouse/lighthouse-core/lib/lh-error.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/lh-error'>;
}
declare module 'lighthouse/lighthouse-core/lib/manifest-parser.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/manifest-parser'>;
}
declare module 'lighthouse/lighthouse-core/lib/network-recorder.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/network-recorder'>;
}
declare module 'lighthouse/lighthouse-core/lib/network-request.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/network-request'>;
}
declare module 'lighthouse/lighthouse-core/lib/page-functions.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/page-functions'>;
}
declare module 'lighthouse/lighthouse-core/lib/sentry.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/sentry'>;
}
declare module 'lighthouse/lighthouse-core/lib/statistics.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/statistics'>;
}
declare module 'lighthouse/lighthouse-core/lib/strings.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/strings'>;
}
declare module 'lighthouse/lighthouse-core/lib/task-groups.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/task-groups'>;
}
declare module 'lighthouse/lighthouse-core/lib/traces/pwmetrics-events.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/traces/pwmetrics-events'>;
}
declare module 'lighthouse/lighthouse-core/lib/traces/tracing-processor.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/traces/tracing-processor'>;
}
declare module 'lighthouse/lighthouse-core/lib/url-shim.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/url-shim'>;
}
declare module 'lighthouse/lighthouse-core/lib/web-inspector.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/lib/web-inspector'>;
}
declare module 'lighthouse/lighthouse-core/report/html/html-report-assets.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/html/html-report-assets'>;
}
declare module 'lighthouse/lighthouse-core/report/html/renderer/category-renderer.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/report/html/renderer/category-renderer'
  >;
}
declare module 'lighthouse/lighthouse-core/report/html/renderer/crc-details-renderer.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/report/html/renderer/crc-details-renderer'
  >;
}
declare module 'lighthouse/lighthouse-core/report/html/renderer/details-renderer.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/report/html/renderer/details-renderer'
  >;
}
declare module 'lighthouse/lighthouse-core/report/html/renderer/dom.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/html/renderer/dom'>;
}
declare module 'lighthouse/lighthouse-core/report/html/renderer/logger.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/html/renderer/logger'>;
}
declare module 'lighthouse/lighthouse-core/report/html/renderer/performance-category-renderer.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/report/html/renderer/performance-category-renderer'
  >;
}
declare module 'lighthouse/lighthouse-core/report/html/renderer/psi.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/html/renderer/psi'>;
}
declare module 'lighthouse/lighthouse-core/report/html/renderer/report-renderer.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/report/html/renderer/report-renderer'
  >;
}
declare module 'lighthouse/lighthouse-core/report/html/renderer/report-ui-features.js' {
  declare module.exports: $Exports<
    'lighthouse/lighthouse-core/report/html/renderer/report-ui-features'
  >;
}
declare module 'lighthouse/lighthouse-core/report/html/renderer/util.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/html/renderer/util'>;
}
declare module 'lighthouse/lighthouse-core/report/report-generator.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/report/report-generator'>;
}
declare module 'lighthouse/lighthouse-core/runner.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/runner'>;
}
declare module 'lighthouse/lighthouse-core/scoring.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/scoring'>;
}
declare module 'lighthouse/lighthouse-core/scripts/manual-chrome-launcher.js' {
  declare module.exports: $Exports<'lighthouse/lighthouse-core/scripts/manual-chrome-launcher'>;
}
