// flow-typed signature: ad064bbb14e451d98d0a43cb37e9690a
// flow-typed version: <<STUB>>/storybook_v^1.0.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook/bin/generate' {
  declare module.exports: any;
}

declare module 'storybook/generators/METEOR/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/addons' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.android' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.ios' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/style' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Welcome/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/template/storybook/addons' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/template/storybook/index.android' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/template/storybook/index.ios' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.android' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/style' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/Welcome/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_NATIVE/template/storybook/storybook' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_SCRIPTS/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT_SCRIPTS/template/src/stories/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/REACT/template/stories/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/SFC_VUE/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/SFC_VUE/template/src/stories/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/UPDATE_PACKAGE_ORGANIZATIONS/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/VUE/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/VUE/template/stories/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/VUE/template/stories/MyButton' {
  declare module.exports: any;
}

declare module 'storybook/generators/VUE/template/stories/Welcome' {
  declare module.exports: any;
}

declare module 'storybook/generators/WEBPACK_REACT/index' {
  declare module.exports: any;
}

declare module 'storybook/generators/WEBPACK_REACT/template/stories/index' {
  declare module.exports: any;
}

declare module 'storybook/lib/detect' {
  declare module.exports: any;
}

declare module 'storybook/lib/has_yarn' {
  declare module.exports: any;
}

declare module 'storybook/lib/helpers' {
  declare module.exports: any;
}

declare module 'storybook/lib/project_types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook/bin/generate.js' {
  declare module.exports: $Exports<'storybook/bin/generate'>;
}
declare module 'storybook/generators/METEOR/index.js' {
  declare module.exports: $Exports<'storybook/generators/METEOR/index'>;
}
declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/index.js' {
  declare module.exports: $Exports<'storybook/generators/REACT_NATIVE_SCRIPTS/index'>;
}
declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/addons.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/addons'
  >;
}
declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/index.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/index'
  >;
}
declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.android.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.android'
  >;
}
declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.ios.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.ios'
  >;
}
declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/index.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/index'
  >;
}
declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/style.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/style'
  >;
}
declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/index.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/index'
  >;
}
declare module 'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Welcome/index.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Welcome/index'
  >;
}
declare module 'storybook/generators/REACT_NATIVE/index.js' {
  declare module.exports: $Exports<'storybook/generators/REACT_NATIVE/index'>;
}
declare module 'storybook/generators/REACT_NATIVE/template/storybook/addons.js' {
  declare module.exports: $Exports<'storybook/generators/REACT_NATIVE/template/storybook/addons'>;
}
declare module 'storybook/generators/REACT_NATIVE/template/storybook/index.android.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE/template/storybook/index.android'
  >;
}
declare module 'storybook/generators/REACT_NATIVE/template/storybook/index.ios.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE/template/storybook/index.ios'
  >;
}
declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.android.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.android'
  >;
}
declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios'
  >;
}
declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/index.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/index'
  >;
}
declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/style.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE/template/storybook/stories/CenterView/style'
  >;
}
declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/index.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE/template/storybook/stories/index'
  >;
}
declare module 'storybook/generators/REACT_NATIVE/template/storybook/stories/Welcome/index.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE/template/storybook/stories/Welcome/index'
  >;
}
declare module 'storybook/generators/REACT_NATIVE/template/storybook/storybook.js' {
  declare module.exports: $Exports<
    'storybook/generators/REACT_NATIVE/template/storybook/storybook'
  >;
}
declare module 'storybook/generators/REACT_SCRIPTS/index.js' {
  declare module.exports: $Exports<'storybook/generators/REACT_SCRIPTS/index'>;
}
declare module 'storybook/generators/REACT_SCRIPTS/template/src/stories/index.js' {
  declare module.exports: $Exports<'storybook/generators/REACT_SCRIPTS/template/src/stories/index'>;
}
declare module 'storybook/generators/REACT/index.js' {
  declare module.exports: $Exports<'storybook/generators/REACT/index'>;
}
declare module 'storybook/generators/REACT/template/stories/index.js' {
  declare module.exports: $Exports<'storybook/generators/REACT/template/stories/index'>;
}
declare module 'storybook/generators/SFC_VUE/index.js' {
  declare module.exports: $Exports<'storybook/generators/SFC_VUE/index'>;
}
declare module 'storybook/generators/SFC_VUE/template/src/stories/index.js' {
  declare module.exports: $Exports<'storybook/generators/SFC_VUE/template/src/stories/index'>;
}
declare module 'storybook/generators/UPDATE_PACKAGE_ORGANIZATIONS/index.js' {
  declare module.exports: $Exports<'storybook/generators/UPDATE_PACKAGE_ORGANIZATIONS/index'>;
}
declare module 'storybook/generators/VUE/index.js' {
  declare module.exports: $Exports<'storybook/generators/VUE/index'>;
}
declare module 'storybook/generators/VUE/template/stories/index.js' {
  declare module.exports: $Exports<'storybook/generators/VUE/template/stories/index'>;
}
declare module 'storybook/generators/VUE/template/stories/MyButton.js' {
  declare module.exports: $Exports<'storybook/generators/VUE/template/stories/MyButton'>;
}
declare module 'storybook/generators/VUE/template/stories/Welcome.js' {
  declare module.exports: $Exports<'storybook/generators/VUE/template/stories/Welcome'>;
}
declare module 'storybook/generators/WEBPACK_REACT/index.js' {
  declare module.exports: $Exports<'storybook/generators/WEBPACK_REACT/index'>;
}
declare module 'storybook/generators/WEBPACK_REACT/template/stories/index.js' {
  declare module.exports: $Exports<'storybook/generators/WEBPACK_REACT/template/stories/index'>;
}
declare module 'storybook/lib/detect.js' {
  declare module.exports: $Exports<'storybook/lib/detect'>;
}
declare module 'storybook/lib/has_yarn.js' {
  declare module.exports: $Exports<'storybook/lib/has_yarn'>;
}
declare module 'storybook/lib/helpers.js' {
  declare module.exports: $Exports<'storybook/lib/helpers'>;
}
declare module 'storybook/lib/project_types.js' {
  declare module.exports: $Exports<'storybook/lib/project_types'>;
}
