// flow-typed signature: d8230b35000a77a4238e8b71cabe9b5c
// flow-typed version: <<STUB>>/winston-logrotate_v^1.3.0/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-logrotate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-logrotate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-logrotate/lib/winston-logrotate' {
  declare module.exports: any;
}

declare module 'winston-logrotate/test/winston-logrotate.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-logrotate/lib/winston-logrotate.js' {
  declare module.exports: $Exports<'winston-logrotate/lib/winston-logrotate'>;
}
declare module 'winston-logrotate/test/winston-logrotate.spec.js' {
  declare module.exports: $Exports<'winston-logrotate/test/winston-logrotate.spec'>;
}
