// flow-typed signature: f037c0374a5bd9150603143a2c587f8f
// flow-typed version: <<STUB>>/@svgr/webpack_v2.4.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/webpack/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/webpack/lib/index.js' {
  declare module.exports: $Exports<'@svgr/webpack/lib/index'>;
}
